version: "3"
services:
  app:
    build: .
    environment:
      - REDIS_HOST=redis
    depends_on:
      - api_cache
      - redis
    ports:
      - "8050:8050"

  api_cache:
    build: ./API_cashe
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
